### ISSUE TITLE
PHP Error in Rewind.php: Var number is not defined

### ISSUE THREAD

**Issue by m4m-simon** [magento-hackathon/MageTrashApp#11]
Notice: Undefined variable: number  in XXXXX/.modman/MageTrashApp/src/app/code/community/Hackathon/MageTrashApp/Block/Adminhtml/System/Config/Form/Fieldset/Modules/Rewind.php on line 91

**Comment by Schrank** [comment]
Thanks for the report! There is no one who maintains this module, so please don't expect a fix.

**Comment by diglin** [comment]
Hi @m4m-simon do you mind please to send a PR ? We may merge it

Thanks
Sylvain

**Comment by m4m-simon** [comment]
done! :)

Viele Grüße
Simon Menzel

--

media4motion Werbeagentur GmbH
Königsweg 11
24103 Kiel

Tel.: +49 (0) 431 - 53 42 04 97
Fax: +49 (0) 431 - 53 42 04 98

menzel@media4motion.com
www.media4motion.com

Geschäftsführer: Nils Karlsson Graeper
Handelsregister Kiel: HRB 10874 KI
USt-IdNr.: DE 24 50 68 0 36
Steuernummer: 19/291/29435

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




Am 03.05.2018 um 13:01 schrieb Diglin GmbH <notifications@github.com>:

**Comment by sylvainraye** [comment]
Merged. Thank you for your contribution. Have a nice day
