### ISSUE TITLE
ERROR:Cannot edit role in backend

### ISSUE THREAD

**Issue by AnthraX1** [magento-hackathon/MageTrashApp#2]
After installed this with username plugin from magentoconnect, I cannot edit roles in backend.

Im using 1.7.02 version

I did some check and the logs showed following:

Apache errorlog:

mod_fcgid: stderr: PHP Fatal error:  Class 'Mage_Trashapp_Helper_Data' not found in /var/www/html/app/Mage.php on line 546

Magento system log:

ERR (3): Warning: include(): Failed opening 'Mage/Trashapp/Helper/Data.php' for inclusion (include_path='/var/www/html/app/code/local:/var/www/html/app/code/community:/var/www/html/app/code/core:/var/www/html/lib:.:/usr/share/pear:/usr/share/php')  in /var/www/html/lib/Varien/Autoload.php on line 93

**Comment by vishveskrish** [comment]
No need to go for the new version. In system.xml , just change module="trashapp" to module="magetrashapp"

 - Punit Advani
