### ISSUE TITLE
Newbie how to use it!

### ISSUE THREAD

**Issue by lgt** [magento-hackathon/MageTrashApp#6]
I'm quite new to magento and I just installed your provided package but I have problems to use it.

I added under `/etc/ununstall.txt`

which contains

`app/code/local/AW/AW_Followupemail
app/etc/modules/AW_Followupemail.xml`

than inside `etc/modules/AW_Followupemail.xml`

I added to the config

```
<config>
   <modules>
      <AW_Followupemail>
         <active>false</active>
         <codePool>local</codePool>
      </AW_Followupemail>
   </modules>
   <uninstall>
      <filename>uninstallfile.txt</filename>
   </uninstall>
</config>
```

After from backend running uninstall just the entry from core_resource is getting removed but not the files. In uninstall.php I don't know what should be placed I supposue some drop steatment but how?

Can you provide a detaliated example please

**Comment by diglin** [comment]
Hi

You can find doc and a sample here: https://github.com/magento-hackathon/MageTrashApp/blob/master/src/app/code/community/Hackathon/MageTrashApp/etc/doc.uninstall.txt

As I see above, you use the wrong config.xml. It must be the config.xml located into the module itself

**Comment by lgt** [comment]
thank you works
